export const FB_AUTH_SUCCESS = 'FB_AUTH_SUCCESS';
export const FB_AUTH_ERR = 'FB_AUTH_ERR';

export const FETCH_DIVE_LOG_STARTED = 'FETCH_DIVE_LOG_STARTED';
export const FETCH_DIVE_LOG_SUCCESS = 'FETCH_DIVE_LOG_SUCCESS';
export const FETCH_DIVE_LOG_ERR = 'FETCH_DIVE_LOG_ERR';
